
<field:vname itemname="申请人姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:vname>

<field:vphone itemname="申请人手机号" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:vphone>

<field:vlx itemname="申请类型" autofield="1" type="select" isnull="true" default="个人,企业"  maxlength="250" page="">
</field:vlx>

<field:vemail itemname="邮件地址" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:vemail>

<field:vcity itemname=" 办理城市" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:vcity>

<field:vmoney itemname="充值金额" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:vmoney>

<field:vbz itemname="备注" autofield="1" type="multitext" isnull="true" default=""  maxlength="250" page="">
</field:vbz>
