
<field:wname itemname="申请人姓名" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wname>

<field:wphone itemname="联系电话" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wphone>

<field:wlx itemname="宴会类型" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wlx>

<field:wtime itemname="宴会举办日期" autofield="1" type="text" isnull="true" default=""  maxlength="250" page="">
</field:wtime>
